carmen/core/urls.py
from django.urls import path

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'core'

urlpatterns = [
    path('',auth_views.login, {'template_name': 'index.html'},name='index-login'),
    path('cadastro/',views.CadastroUser.as_view(),name='cadastro'),
    path('cadastro/dashboard/',views.Dashboard.as_view(),name='dashboard'),
    path('cadastro/logout/',auth_views.logout, {'template_name': 'conta/back.html'}, name='logout'),
    path('cadastro/dashboard/jogo/<pk>/',views.Game.as_view(), name='jogo'),
]

carmen/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('carmen.core.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carmen/core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Pergunta(models.Model):

    texto = models.TextField()
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
    	return self.texto

class Relaciona(models.Model):

    ir_para = models.ForeignKey(Pergunta, on_delete=models.CASCADE,
        help_text='Esse campo serve para direcionar para qual pergunta deve ter as opções'
    )
    relaciona = models.ForeignKey(Pergunta, on_delete=models.CASCADE, related_name='relacionas',
        help_text='Esse campo serve para mostrar em qual pergunta o botão deve aparecer para\
        se relacionar com a pergunta de cima'
    )

    def __str__(self):
    	return str(self.ir_para)

carmen/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from . import models
from . import form
from django.http import HttpResponseRedirect

# Create your views here.

class CadastroUser(CreateView):

    model = User
    template_name = 'conta/cadastro.html'
    form_class = form.RegisterForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return HttpResponseRedirect('/')

class Dashboard(TemplateView):

    template_name = 'conta/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)

        context['jogo'] = models.Pergunta.objects.all().first()

        return context

class Game(DetailView):

    model = models.Pergunta
    template_name = 'resultado/jogo.html'

    def get_context_data(self, **kwargs):
        context = super(Game, self).get_context_data(**kwargs)

        rel = models.Relaciona.objects.filter(relaciona_id=self.kwargs.get('pk',None))
        print(rel)

        context['rel'] = rel

        return context

carmen/core/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt-br" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% if user.is_authenticated %}
      <title>Carmen Sandiego | {{ request.user }}</title>
    {% else %}
      <title>Carmen Sandiego</title>
    {% endif %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
    integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'core:index-login' %}">Carmen Sandiego</a>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'core:cadastro' %}">Cadastro<span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
            </li>
            {% else %}
              <li class="nav-item">
              <a class="nav-link" href="{% url 'core:index-login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>

    {% block content %}{% endblock %}
  </body>
</html>

carmen/core/templates/conta/back.html
{% extends "base.html" %}

{% block content %}

	<h3>Esperamos que você volta sempre!</h3>

	<a href="{% url 'core:index-login' %}" class="btn btn-default">Fazer login novamente</a>

	<a href="{% url 'core:cadastro' %}" class="btn btn-default">Quero me cadastrar</a>

{% endblock %}

carmen/core/templates/conta/cadastro.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="container">
  <div class="login-form">
  <div class="main-div">
      <div class="panel">
       <h2>Cadastro do usuário</h2>
       <p>Por favor entre com um e-mail e senha valida.</p>
     </div>
    <form id="Login" method="post">
      {% csrf_token %}

      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {% render_field field class="form-control" placeholder=field.label %}
          {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}
        <button type="submit" class="btn btn-primary">Registra-se</button>

    </form>
  </div>
  </div>
</div>
{% endblock %}

carmen/core/templates/conta/dashboard.html
{% extends "base.html" %}

{% block content %}
  <a href="{% url 'core:jogo' jogo.pk %}" class="btn btn-primary">Começar a jogar</a>
{% endblock %}

carmen/core/templates/index.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="container">
  <div class="login-form">
  <div class="main-div">
      <div class="panel">
       <h2>Login do usuário</h2>
       <p>Por favor entre com um e-mail e senha valida.</p>
     </div>
    <form id="Login" method="post">
      {% csrf_token %}

      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {% render_field field class="form-control" placeholder=field.label %}
          {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}
        <button type="submit" class="btn btn-primary">Login</button>

    </form>
  </div>
  </div>
</div>
{% endblock %}

carmen/core/templates/resultado/jogo.html
{% extends "base.html" %}

{% block content %}
  <div class="lado-img">
    <img src="{{ object.imagem.url }}">
  </div>
  <div class="lado">
      <p>
        {{ object.texto|safe }}
      </p>
    <div class="">
        {% for r in rel %}
          Va para <a href="{% url 'core:jogo' r.ir_para_id %}" class="btn btn-primary" name='{{ r.relaciona_id }}'>{{ r.ir_para_id }}</a>
        {% endfor %}
    </div>
  </div>

{% endblock %}